### ISSUE TITLE
Does grl support a Kuka Kr6 robot with KRC4?

### ISSUE THREAD

**Issue by yaozr** [ahundt/grl#101]
Trying to find ROS package working with Kr6 and happen to notice your work, just wonder as the question says...

**Comment by ahundt** [comment]
Don't have a KR6 one but if it uses sunrise there is a good chance it will
work with relatively minor adaptation. Much easier than starting from
scratch! I'm happy to accept pull requests and provide advice where I can.

On Friday, June 24, 2016, yaozr <notifications@github.com> wrote:

> Trying to find ROS package working with Kr6 and happen to notice your
> work, just wonder as the question says...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ahundt/grl/issues/101>, or mute the thread
> <https://github.com/notifications/unsubscribe/AADZwLEG-9t2C8nhGXQne6yXL5HK5DZGks5qPKy2gaJpZM4I-Q2t>
> .
>


-- 
Cheers!
Andrew Hundt

Ph.D. Student
Johns Hopkins University
