### ISSUE TITLE
Atracsys FlatBuffers Logging

### ISSUE THREAD

**Issue by ahundt** [ahundt/grl#143]
We need to save and load fusiontrack data from a file, the functions to do this (toFlatBuffer) are partially implemented, but don't yet save all of the data.

Finish implementation of data conversion API:
- [x] FlatBuffer generation in [FusionTrackToFlatBuffer.hpp](https://github.com/ahundt/grl/blob/master/include/grl/sensor/FusionTrackToFlatbuffer.hpp)
- [x] [FusionTrack.fbs](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/FusionTrack.fbs)
- [x] [LogKUKAiiwaFusionTrack.fbs](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/LogKUKAiiwaFusionTrack.fbs)
- [x] Ensure Every data element defined in [TimeEvent](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/Time.fbs#L13) is properly collected and logged
- [x] save flatbuffers file containing buffers of type [LogKUKAiiwaFusionTrack](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/LogKUKAiiwaFusionTrack.fbs) to disk with [flatbuffers/util.h](https://github.com/google/flatbuffers/blob/master/include/flatbuffers/util.h)
- [x] Add tests
- [x] create pull request so code can be reviewed
- [x] Document how to use the new API

Important code:
- [FusionTrack.hpp](https://github.com/ahundt/grl/blob/master/include/grl/sensor/FusionTrack.hpp)
- struct definitions are in ftkInterface.h

-------------------------------------------------------------------------------------------------------------------------------
- [x]  Create a new function flatbuffers::Offset<grl::flatbuffer::FusionTrackMessage>
toFlatBuffer(flatbuffers::FlatBufferBuilder &fbb, const grl::sensor::FusionTrack &fusiontrack, const grl::sensor::FusionTrack::Frame) in [FusionTrackToFlatBuffer.hpp](https://github.com/ahundt/grl/blob/master/include/grl/sensor/FusionTrackToFlatbuffer.hpp) to record FusionTrackMessage (in [FusionTrack.fbs](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/FusionTrack.fbs)
- [x] timestamp:double is from fusiontrack->frame.imageHeader.timestampUS * microsecToSec;
- [x] geometries:[ftkGeometry] is from [FusionTrack.hpp](https://github.com/ahundt/grl/blob/master/include/grl/sensor/FusionTrack.hpp)->class FusionTrack -> struct Params -> std::vector<MarkerModelGeometry> markerModelGeometries
- [x] timeEvent:TimeEvent is defined in [TimeEvent](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/Time.fbs#L13), which is used in [LogKUKAiiwaFusionTrack.fbs](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/LogKUKAiiwaFusionTrack.fbs) -> table LogKUKAiiwaFusionTrack states -> table KUKAiiwaFusionTrackMessage; the values are from  FusionTrack.hpp->class FusionTrack -> Class Frame -> TimeEvent TimeStamp

Before assign any value to timeEvent, firstly we should define a new function writing the timeEvent to flatbuffer. 

- [x] frames:[FusionTrackFrame] is the vector of FusionTrackFrame, which is defined in the values are from  [FusionTrack.hpp](https://github.com/ahundt/grl/blob/master/include/grl/sensor/FusionTrack.hpp)->class FusionTrack -> Class Frame .
- New table (table FusionTrackParameters) has been added in [FusionTrack.fbs](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/FusionTrack.fbs) to record data that doesn't change often.

----------------------------------------------------------------------------------------------------------------------------------
- [x] Complete four toFlatBuffer functions in [FusionTrackToFlatBuffer.hpp](https://github.com/ahundt/grl/blob/master/include/grl/sensor/FusionTrackToFlatbuffer.hpp).  (10/18)
- TimeEvent
- FusionTrackMessage
- KUKAiiwaFusionTrackMessage 
- LogKUKAiiwaFusionTrack.
UNION (deviceState:DeviceState) in  [LogKUKAiiwaFusionTrack.fbs](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/LogKUKAiiwaFusionTrack.fbs) doesn't work now.
- [x] Save flatbuffers file containing buffers of type  [LogKUKAiiwaFusionTrack.fbs](https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/LogKUKAiiwaFusionTrack.fbs)  to disk with [flatbuffers/util.h](https://github.com/google/flatbuffers/blob/master/include/flatbuffers/util.h) (10/20-10/22) 

    As for this part, I think we should store all the flatbuffer stuff physically, and then get flatbuffer files such as [monsterdata_test.mon](https://github.com/google/flatbuffers/blob/master/include/flatbuffers/util.h).
   The toFlatBuffer functions are designed to write the bytes to a file, and then send them over the network.here can we get the flatbuffer disk fill?
   Then we should use [buffer_pointer](https://google.github.io/flatbuffers/flatbuffers_guide_tutorial.html) and [flatbuffers/util.h](https://github.com/google/flatbuffers/blob/master/include/flatbuffers/util.h) to load, read and deserialize a FlatBuffer, convert all the parameter types into string, then Save it to disk.
   Don't forget to refer to [the example](https://costar-jhu.slack.com/files/U0GP1NFN2/F7B88FQPN/distributed_systems_cs437.zip) .

- [x] Add test.
    Example for test part [KukaLBRiiwaVrepPluginTest.cpp](https://github.com/ahundt/grl/blob/7697615fa2c47994ece8af73553f6005cbcb80e6/test/KukaLBRiiwaVrepPluginTest.cpp).
   [fusionTrackTest.cpp](https://github.com/ahundt/grl/blob/868e5fd2b42144729997e69f62bf2fc88da8c1ef/test/fusionTrackTest.cpp) add another case Boost_Auto_Test_Case (maybe need to edit the function).
- [x] add atracsys logging to V-REP plugin
- [x] run v-rep and collect a log file of the motion of the real robot.

**Comment by Chunting** [comment]
Done
