### ISSUE TITLE
Combined Atracsys + Kuka logging

### ISSUE THREAD

**Issue by ahundt** [ahundt/grl#146]
Depends on:
- https://github.com/ahundt/grl/issues/140 Kuka
- https://github.com/ahundt/grl/issues/143 Atracsys

Fill out and read/write:
-
 https://github.com/ahundt/grl/blob/master/include/grl/flatbuffer/LogKUKAiiwaFusionTrack.fbs

**Comment by Chunting** [comment]
Done.
