### ISSUE TITLE
Assign values to EulerPoseParams

### ISSUE THREAD

**Issue by rkojcev** [ahundt/grl#95]
@ahundt  #94 was a good discussion. :+1: 

I still did not get an answer how do you assign values to a the EulerPoseParams. This will help me move on and start filling out the table CartesianImpedenceControlMode.

Thanks :)

**Comment by ahundt** [comment]
There should be a function starting with "create" such as
CreateEulerPoseParams()
for each data type in the flatbuffer headers. They are generated in the
build/include folder you generated with cmake. The easiest explanation is
in the flatbuffers doc/ example. Let me know if you need more details, I
can explain more if needed.

On Monday, June 6, 2016, Risto Kojcev <notifications@github.com> wrote:

> @ahundt <https://github.com/ahundt> #94
> <https://github.com/ahundt/grl/issues/94> was a good discussion. 👍
>
> I still did not get an answer how do you assign values to a the
> EulerPoseParams. This will help me move on and start filling out the table
> CartesianImpedenceControlMode.
>
> Thanks :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ahundt/grl/issues/95>, or mute the thread
> <https://github.com/notifications/unsubscribe/AADZwFQH-oPOOnJKzCbSTQ2RNBCqJnuvks5qJDd9gaJpZM4Iu_s8>
> .
>


-- 

Cheers!
Andrew Hundt

**Comment by rkojcev** [comment]
Closing this one.
